### ISSUE TITLE
Expose access to `archived` state

### ISSUE THREAD

**Issue by thomasvdpol** [buildkite/terraform-provider-buildkite#131]
We've got a couple of archived pipelines, and a few more that probably should be archived. It'd be nice to be able to manage this through Terraform. I had a quick look around in the code but I'm not familiar enough with Go to see an obvious change to make.

**Comment by yob** [comment]
Yer, this would be a neat feature to add. I think it should be possible too - there are `pipelineArchive` and `pipelineUnarchive` graphql mutations ([docs](https://buildkite.com/user/graphql/documentation)).

The only messy part is that I assume we'd need to add an `archived = true/false` property to the pipeline resource, and changing it would require a graphql API call in addition to the `pipelineUpdate` mutation. I don't think that's a blocker though.

We're pretty busy for the next little while so I don't think we'll have time to do this right away, but if you're keen to have a crack I've hacked together a very rough diff that won't compile but should show a rough direction this could take: https://gist.github.com/yob/92a29820a01ac4bd38f47f05d6036809

**Comment by jradtilbrook** [comment]
Looks like the `pipelineUpdate` mutation input type `PipelineUpdateInput` has an `archived` field now so this should be rather simple to add. 

One edge case I can think of is if you wanted to create a pipeline and mark it archived as well - that would require 2 calls because the `PipelineCreateInput` doesn't have an archived field (nor should it IMO). I can't see someone doing this regularly, but we should be able to support that pretty easily as well - and if we don't, it would just take a subsequent `terraform apply` to detect the change and apply it.

**Comment by jradtilbrook** [comment]
Scratch that, the `archived` property on `PipelineUpdateInput` is deprecated and due for removal on 2022-06-01.

2 requests it is!

**Comment by jradtilbrook** [comment]
Having another look at this I don't think it is something we will implement. We have added a `archive_pipeline_on_delete` provider configuration option so that when destroying a pipeline, it can be archived instead of outright deleted. Maintaining an archived pipeline in terraform is not the current direction we want to take
