### ISSUE TITLE
Standardise IDs used for importing resources

### ISSUE THREAD

**Issue by yob** [buildkite/terraform-provider-buildkite#143]
In #140 @thomasvdpol observed that we're inconsistent with the type of ID we use for importing resources. Some use the graphql ID, some use the UUID. It'd be nice to standardise on a single type of ID (or consistently support both I guess).

If we pick one, we should gracefully transition and support both kinds of ID on the resources that need to change for a while.

Here's the ID types we currently require:

* agent_token: graphql ID
* pipeline: graphql ID
* pipeline_schedule: `<org slug>/<pipeline slug>/<schedule uuid>`
* team: graphql ID

**Comment by jradtilbrook** [comment]
There are some use cases of slugs over ID's or vice-versa as well. I'm not sure which way we should lean for that - I kinda like slugs better for readability of the terraform files themselves. But perhaps we should use ID's in resources and allow "lookups" via datasources which can use either/both in order to retrieve details about a resource?

Do you have any opinion or thoughts @yob @jeremybumsted?
