### ISSUE TITLE
Question: is it possible to set pipeline as archived rather than deleting it?

### ISSUE THREAD

**Issue by williamblevins** [buildkite/terraform-provider-buildkite#182]
When removing a buildkite_pipeline from Terraform, is it possible to just archive the pipeline and remove the resource rather than outright deleting it?

**Comment by jradtilbrook** [comment]
Hi @williamblevins we have this PR #177 which adds support for archiving a pipeline. 

However, if you remove it from your terraform config, it will get deleted. You can look into manually removing it from state so that terraform no longer tracks it and then will not try delete it if you remove it from your config. https://www.terraform.io/cli/commands/state/rm
