### ISSUE TITLE
Use proposed `Pipeline.WebHookUrlHash` field to check state changes

### ISSUE THREAD

**Issue by david-poirier** [buildkite/terraform-provider-buildkite#428]
When performing a plan on a `buildkite_pipeline` resource the credentials used require `MANAGE_BUILD_AND_READ` access to the pipeline referenced due to the use of the `webhookURL` field in the GraphQL query, which is considered sensitive. See https://github.com/buildkite/terraform-provider-buildkite/blob/f60b1f45eed2b32786abe5c97e51d6931ef2c9cd/buildkite/generated.go#L11898

This requirement prevents us from using read-only users to perform Terraform plan operations.

Instead of querying this field I propose adding a `webhookURLHash` field to the GraphQL object, which would contain a hash of the `webhookURL` field value. This would allow comparison between the current and proposed values of `webhookURL` without revealing the current value.

**Comment by james2791** [comment]
Thanks for the raise on this @david-poirier!

We'll assess what this means for the provider and what might change/needs changing, and will loop with you on when we know the direction that we'll be taking 🙂

**Comment by jradtilbrook** [comment]
I think adding a new field to the API for this purpose is probably out of scope. What I think we could do (and still needs investigating) is not to query that webhook URL after the pipeline has been created. Its a fixed endpoint that doesnt change for the life of a pipeline, so we really only need it once upon creation. That would achieve the same thing I think

We'll look into how feasible that is in the next few weeks

**Comment by james2791** [comment]
Hey @david-poirier!

Should mention first thing - happiest of New Years for 2024! Hope you all had an amazing break and entry into the new year.

Just a passing update on Jarryd's note above - we did some assessments and work on this over the latter part of last month - and [release](https://github.com/buildkite/terraform-provider-buildkite/releases/tag/v1.2.0) `v1.2.0` comes with an [adjustment](https://github.com/buildkite/terraform-provider-buildkite/pull/450) to the pipeline resource so that only creates will read in the `webhookURL` - when you can, let us know if that fits the need as above!
