### ISSUE TITLE
webhookUrl no longer available on `buildkite_pipeline`

### ISSUE THREAD

**Issue by patrickhayes-at** [buildkite/terraform-provider-buildkite#480]
**Describe the bug**
webhookUrl was removed as a field from the `buildkite_pipline` terraform resource in 1.2.0 (see https://github.com/buildkite/terraform-provider-buildkite/issues/428)

This is a regression; we previously used terraform to manage our webhooks from Buildkite pipelines and persist them to GitHub repositories (with [repository_webhook](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_webhook.html). After 1.2.0, the webhook URL is only returned on create operations, which impedes our ability to do this.

Can this functionality be restored?

**Comment by jradtilbrook** [comment]
Hey @patrickhayes-at, the `webhook_url` field was not actually removed, its still accessible.

However, the API was changed to only return a value for that field upon initial creation. It is no longer possible to read the value from the API after creating the pipeline. So we updated the provider to only set the value in state upon creation and to ignore it when reading/updating a resource in terraform. This shouldn't cause any problems for users creating pipelines with terraform, although if you import an existing pipeline to terraform, that field will be missing and needs to be manually set.

Having said that, if you have experienced something different to that, please reopen this issue with more details and we can investigate

**Comment by patrickhayes-at** [comment]
> It is no longer possible to read the value from the API after creating the pipeline.

Is this true? I can see webhook URLs for existing pipelines in the GraphQL API explorer.

> although if you import an existing pipeline to terraform, that field will be missing and needs to be manually set.

Yes, this is exactly the problem. It's not viable for us to read and persist this value at the time of pipeline creation when we have pre-existing pipelines we want to work with in terraform.

**Comment by patrickhayes-at** [comment]
I don't appear to have permission to reopen this issue, but we are still affected per the above comment

**Comment by mcncl** [comment]
@patrickhayes-at I've re-opened it for you 🙂

**Comment by jradtilbrook** [comment]
Hi @patrickhayes-at thanks for getting back to us, I didn't realise you wouldn't be able to reopen it yourself 👍

I've done some more digging and realised I was wrong, that was not the reason for removing the webhook url attribute. We removed it to accommodate a "read-only" token being used in a plan phase for extra security. Ie a flow that would generate a terraform plan as part of a PR build but wouldn't apply it - to aid in PR review, etc.

However, this has broken your flow. We assumed that terraform import also requiring a state edit to put the webhook url into state wouldn't be a major problem as its a manual process anyway and done fairly rarely. Would you say that is not the case for you? Could you elaborate on your specific use-case? So we can better understand the problem and potential solutions

**Comment by tgoldthorpe** [comment]
Hello @jradtilbrook, I’ve been running into this issue recently as well.

I've got a repo where we are managing GitHub Repositories via yaml files so that developers only need to make their changes there instead of writing Terraform code. This repo has some custom code to handle existing repos and their nested resources like branch protection and webhooks. We import all the existing resources into the state file prior to doing a terraform plan so we can apply the opinionated settings to the resources.

We’ve been building out support for Buildkite Pipelines so devs don’t need to provide the webhook in the yaml files and instead will be handled with the `webhook_url` from the Buildkite Pipeline. I’ve been recently noticing errors like below while we have been testing it prior to release and I think it is related to this:
```
Error: "configuration.0.url": required field is not set
```

I’d say over 90% of the repos/pipelines already exist with our set up, so with our current approach we'd definitely need this `webhook_url` accessible via the import step, unless there was another way we can obtain it?

Let me know if you'd like more info or if you'd like me to raise a separate issue.

Thanks!

**Comment by jradtilbrook** [comment]
Ohh wow that is not a usecase that has ever crossed my mind. Thanks for sharing @tgoldthorpe 

So is it correct to say you aren't actually using terraform state between applies? You basically start again for each terraform import/apply that you do? Which means import is a common part of the flow. 

I think we have a way around this that we are looking at and hopefully can have something out in the next week.

**Comment by tgoldthorpe** [comment]
Yeah, I can imagine our usage is a bit of an edge case! Not quite, we still use the state file between applies. However the first time a repo is added to a team's config file (i.e. in a yaml file but not as a resource in the state file) we check if it exists via API calls and run a terraform import across it so that terraform doesn't try and create a resource that already exists.

Afterwards we run the terraform plan and apply. Any drift from the opinionated settings is applied and new resources are created. If there's no additions to the configs it'll just do the plan and apply and no imports.

Sounds good, thanks for looking into this so quickly! Very much appreciated 😃

**Comment by cysp** [comment]
FWIW, my organisation recently updated the buildkite terraform provider to v1 before beginning a series of terraform imports of code repositories and associated buildkite pipelines and have started encountering this same problem of webhook urls being unknown for an imported pipeline.

I wouldn't call our setup particularly oddball, we're modelling buildkite_pipeline resources in terraform and then also modelling github_repository_webhook resources, using a buildkite pipeline's webhook_url attribute. All of these resources (github_repository, buildkite_pipeline, github_repository_webhook) already exist and are being imported into terraform management.
This import workflow seemed to work perfectly well using the v0 terraform provider. 😿

**Comment by 42atomys** [comment]
We facing the same issue on our organization. We currently migrate our buildkite definition through terraform and now we cannot anymore `terraform import` existing pipeline and create our `github_repository_webhook` resource due to the missing `webhook_url` field

Error: `The argument "configuration.0.url" is required`

```terraform
resource "buildkite_pipeline" "pipeline" {
  for_each   = { for pipeline in var.pipelines : pipeline.name => pipeline }

  name                                     = each.key
  # ....  
}
resource "github_repository_webhook" "webhooks" {
  for_each = { for pipeline in var.pipelines : pipeline.name => pipeline }

  repository = each.key

  configuration {
    url          = buildkite_pipeline.pipeline[each.key].webhook_url
    content_type = "form"
    insecure_ssl = false
  }

  active = true

  events = [
    "deployment",
    "deployment_status",
    "pull_request",
    "push",
  ]
}
```

**Comment by mf-lit** [comment]
Similar issue here, we've got a lot of manually-create pipelines we plan to import into terraform. So manually importing them into state is not a practical solution for us.

**Comment by mcncl** [comment]
Hey folks 👋

Thanks for your feedback! Sounds like we didn’t fully consider the impact of the initial change. 😞 

We have a fix for this ready to go, so we’ll release it this week, likely Monday as that’s when the Australian team will be back online, so any folks in the US will probably have a new release waiting for them to upgrade to when they wake, and folks in Australia, NZ etc will have a fix early on in their work day. 

Thanks for the patience and the input, it’s helped us massively and we’re grateful of the community ❤️
