### ISSUE TITLE
[bug report] AttributeName("provider_settings"): invalid JSON error

### ISSUE THREAD

**Issue by runlevel5** [buildkite/terraform-provider-buildkite#501]
**Describe the bug**

Getting `AttributeName("provider_settings"): invalid JSON error` error

Impacted version: v1.5.1

**To Reproduce**

The error has popped up in pulumiverse/pulumi-buildkite when it bumps its dependency to v1.5.1

1. Simply create a new pulumi stack then `pulumi up`

**Expected behavior**
No error

**Additional context**

This issue only impacts upgrading stack that was created with pre-1.4.1 version to 1.5.x

Please my full error trace at https://gist.github.com/runlevel5/804c363fa0ca81a404d8bbb5a29d8bbd

**Comment by mcncl** [comment]
@runlevel5 thanks for the report and opening the issue. I don't see anything in recent (1.5.x) that would have caused this, so I'm taking a guess that the initial stack was actually created pre-v1.x.x. There is a note in the [upgrading doc](https://github.com/buildkite/terraform-provider-buildkite/blob/main/docs/guides/upgrade-v1.md) that mentions a change in the way `provider_settings` is used.

The [previous version](https://github.com/buildkite/terraform-provider-buildkite/blob/a36642a6ba532032c0becea859489a704a3604c6/buildkite/resource_pipeline.go#L95) (prior to v1) used an array of provider settings.

```go 
ProviderSettings                     []*providerSettingsModel `tfsdk:"provider_settings"`
```

Whereas the [newer model](https://github.com/buildkite/terraform-provider-buildkite/blob/113d32f3f5d557f551dce4adb98b949ccd036ef4/buildkite/resource_pipeline.go#L88) is a pointer to an object/struct.

```go
	ProviderSettings                     *providerSettingsModel `tfsdk:"provider_settings"`
```

It is likely just a case of modifying your pipeline to use the new settings embedded block, rather than the previous config.
