### ISSUE TITLE
Add Support for Archiving Pipelines

### ISSUE THREAD

**Issue by jmandel1027** [buildkite/terraform-provider-buildkite#508]
## What

We need to add support for archiving buildkite pipelines via `buildkite_pipeline` terraform provider. 

## Why

We have a IAC tool that our devs at Block are using to manage Buildkite Pipelines as yaml / TF, and devs are occasionally going through the Buildkite UI to `archive` pipelines which will break their shard of TF state. If we have the ability to Archive via TF provider then we can safely allow teams to archive things instead of a wholesale deletion from our gitops tool for pipeline configs.

**Comment by jradtilbrook** [comment]
Hi @jmandel1027 thanks for raising this 👍

We actually do have support for this through a provider config option `archive_pipeline_on_delete`. Setting this to true will archive the pipeline when its destroyed in terraform instead of deleting it

**Comment by chakrit** [comment]
@jradtilbrook This does not work for the case where we want some pipelines to be archived and others to be deleted at the same time.

Shouldn't the provider option match what we can do through the UI? On buildkite UI we can individually archive/delete each individual ones.

**Comment by jradtilbrook** [comment]
Hey @chakrit im no longer on the team maintaining this so I'll loop someone else in: @mcncl 

Although I do think it's a bit of a chicken/egg problem. If you remove the resource from terraform spec files, how do you instruct the provider to archive that pipeline instead of delete it as the resource is not present. You'd have to first add an archive=true,apply, then remove or something like that. Or perhaps you keep the pipeline on terraform but just add an archive=true field. 

I'll leave it with the current team to get back to you

**Comment by mcncl** [comment]
@chakrit 👋 as Jarryd mentioned; the way to do this right now is to archive a pipeline via the resource itself, then do as you wish with that resource; delete it and remove from state, keep it archived etc.

The reason this is a global setting is because it might be a nice option to be able to archive deleted pipelines rather than actually remove them; perhaps for governance and so on. The provider currently behaves at the UI does; you can archive a pipeline, then unarchive it if you wish, or delete a pipeline (`terraform destroy`). Adjusting the behaviour further isn't something we'll be looking at at the moment, like I mentioned, it currently behaves as the web app does, with some additional functionality (you can't set `archive_on_delete` in the web app).
