### ISSUE TITLE
Adding schedules resource type

### ISSUE THREAD

**Issue by runlevel5** [buildkite/terraform-provider-buildkite#58]
My work happens to need schedules set up so I am thinking about adding this feature but unsure how you would like the interface to be like.

Here are few options that I come up with:

```tf
# DSL in the `buildkite_pipeline` resource
resource "buildkite_pipeline" "repo1" {
  schedules = [
    {
      cron_interval: string,
      description: string,
      build_message: string,
      build_commit: string,
      build_branch: string,
      builld_env: { key: value }
    }
  ]
}
```

OR

```tf
# `buildkite_schedules` resource
resource "buildkite_schedules" "sched1" {
    cron_interva=string,
    description=string,
    build_message=string,
    build_commit=string,
    build_branch=string,
    builld_env={ key: value }
}

resource "buildkite_pipeline" "repo1" {
  schedules = [sched1]
}
```

Thoughts?

**Comment by jradtilbrook** [comment]
I think nested makes most sense like option 1.  
The other one I can think of is to have it separate like you have but to reverse how they are linked. So instead of the pipeline have a schedules field that you add a logical resource to, you add the pipeline to schedules resource (FWIW it probably wouldn't work the way you have specified for option 2 because of the dependency on creating a pipeline before creating a schedule but terraform would likely resolve to trying to create the schedule first since the pipeline needs the link to it).

Not sure if that description makes sense. Either way, I think your first option is a nicer one - it is also closer to how the teams work (although they are a valid resource on their own unlike schedules)

**Comment by jradtilbrook** [comment]
Hey @runlevel5 I'm not sure if you are still interested in implementing this but I've changed my mind on this.

I think having a separate resource for a schedule like `buildkite_scheduled_pipeline` would be better. With this design I think it would be nicer to add schedules at a later point and have them logically separated from the pipeline
